// @ts-check
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const parser = await readFile(path.join(root, 'src/parser.c'), 'utf8');
const predicates = [1, 2].map((index) => {
  const match = parser.match(
    new RegExp(
      `\\b(ts_lex_\\w+\\(ts_lex_aux_sym__template_name_token1_character_set_${index}_ascii,[^\\n;]*?lookahead\\))`
    )
  );
  assert.ok(match?.[1], `Missing generated template-name predicate ${index}`);
  return match[1];
});
await mkdir(path.join(root, '.tmp'), { recursive: true });
const temporary = await mkdtemp(path.join(root, '.tmp/letter-ranges-'));
try {
  const source = path.join(temporary, 'ranges.c');
  const executable = path.join(temporary, 'ranges');
  await writeFile(
    source,
    `
#include <stdio.h>
#include <stdlib.h>
#include ${JSON.stringify(path.join(root, 'src/parser.c'))}

void *tree_sitter_kotlin_external_scanner_create(void) { abort(); }
void tree_sitter_kotlin_external_scanner_destroy(void *payload) { abort(); }
bool tree_sitter_kotlin_external_scanner_scan(void *payload, TSLexer *lexer, const bool *valid) { abort(); }
unsigned tree_sitter_kotlin_external_scanner_serialize(void *payload, char *buffer) { abort(); }
void tree_sitter_kotlin_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) { abort(); }

int main(void) {
  for (int table = 0; table < 2; table++) {
    printf("static const uint32_t %s[][2] = {\\n", table ? "NAME_PART_RANGES" : "LETTER_RANGES");
    int32_t start = -1;
    for (int32_t lookahead = 128; lookahead <= 0x110000; lookahead++) {
      bool member = lookahead < 0x110000 && (table ? ${predicates[1]} : ${predicates[0]});
      if (member && start < 0) start = lookahead;
      if (!member && start >= 0) {
        printf("    {0x%x, 0x%x},\\n", (unsigned)start, (unsigned)(lookahead - 1));
        start = -1;
      }
    }
    printf("};\\n\\n");
  }
}
`
  );
  execFileSync('cc', ['-std=c11', '-I', path.join(root, 'src'), source, '-o', executable]);
  const tables = execFileSync(executable, { encoding: 'utf8' });
  await writeFile(
    path.join(root, 'src/letter_ranges.h'),
    `// Generated by script/generateLetterRanges.js from the parser's template-name predicates.
#ifndef TREE_SITTER_KOTLIN_LETTER_RANGES_H_
#define TREE_SITTER_KOTLIN_LETTER_RANGES_H_

#include <stdint.h>

${tables}#endif
`
  );
} finally {
  await rm(temporary, { recursive: true, force: true });
}
